wandb_version: 1

batch_size:
  desc: null
  value: 32
num_channels:
  desc: null
  value: 3
greyscale:
  desc: null
  value: true
pretrained:
  desc: null
  value: true
checkpoint:
  desc: null
  value: ./experiments/pneumothorax_4_norm_1000e_400p_no_pretrained_2025-10-02T20:04:40.851053.pt
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1759409184.0
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.12.3
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
